// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
// app/layout.jsx
// app/layout.jsx
import './globals.css';
import { BookmarkProvider } from '../context/BookmarkContext';
import Header from '../components/Header';
// import { BookmarkProvider } from '@/context/BookmarkContext';


export const metadata = {
  title: 'HR Dashboard',
  description: 'Mini HR Performance Dashboard',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100 min-h-screen flex flex-col">
        <BookmarkProvider>
          <Header />
          <main className="flex-grow container mx-auto p-4">{children}</main>
        </BookmarkProvider>
      </body>
    </html>
  );
}

